#callout names
# do not edit bungie callouts
bungie_callouts = [
    "ascend",
    "black garden",
    "commune",
    "dark",
    "drink",
    "earth",
    "enter",
    "fleet",
    "give",
    "grieve",
    "guardian",
    "heart",
    "hive",
    "kill",
    "light",
    "love",
    "pyramid",
    "remember",
    "scorn",
    "stop",
    "tower",
    "traveler",
    "witch queen",
    "witness",
    "worm",
    "worship"
]
# custom callouts should be in same index as official ones above
custom_callouts = [
    "umbrella",
    "green",
    "prism",
    "dark",
    "chalice",
    "earth",
    "vault of glass",
    "fleet",
    "face",
    "hole in guy",
    "ghost",
    "heart",
    "hive",
    "circle",
    "light",
    "peppermint",
    "pyramid",
    "brain",
    "forsaken",
    "square",
    "tower",
    "traveler",
    "witch queen",
    "witness",
    "snake",
    "salvation"
]